/* SOCKET.IO message Types */
export const url = '192.168.43.223'
export const PING_SOCKETIO_TYPE = 'PING'
export const PONG_SOCKETIO_TYPE = 'PONG'
export const MESSAGE = 'MESSAGE'
export const QUIZ_FINISHED = 'QUIZ FINISHED'
export const GET_QUIZ = 'GET QUIZ'
export const START_QUIZ = 'START QUIZ'
export const NEXT_QUESTION = 'NEXT QUESTION'
export const GET_IMAGE = 'GET IMAGE'
export const ADD_QUIZ = 'ADD QUIZ'
export const ALL_TYPES_QUIZZ = 'ALL TYPES QUIZZ'
export const INDIVIDUEL_QUIZZ = 'INDIVIDUEL QUIZZ'
export const COLLABORATIVE_QUIZZ = 'COLLABORATIVE QUIZZ'
export const TANGIBLE_QUIZZ = 'TANGIBLE QUIZZ'
export const NO_TANGIBLE_QUIZZ = 'NO TANGIBLE QUIZZ'
export const PASS_TO_NEXT = 'PASS TO NEXT'
